# Generated by Django 3.1.1 on 2020-09-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_remove_myblog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='text',
            new_name='body',
        ),
    ]
