# Generated by Django 3.1.1 on 2020-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_auto_20200928_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='title_tag',
            field=models.CharField(default='hello', max_length=255),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
