# Generated by Django 3.1.1 on 2020-09-28 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_auto_20200928_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myblog',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
