# Generated by Django 3.1.1 on 2020-09-30 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywebsite', '0005_auto_20200928_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
