# Generated by Django 3.1.1 on 2020-09-30 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_auto_20200930_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
