# Generated by Django 3.1.1 on 2020-09-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0008_auto_20200930_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='likes',
        ),
    ]
