# Generated by Django 3.1.1 on 2020-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0009_remove_myblog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='snippet',
            field=models.CharField(default='Click Link Above to Read Blog Post...!!', max_length=255),
        ),
    ]
