# Generated by Django 3.1.1 on 2020-10-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0014_commet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
    ]
