# Generated by Django 3.1.1 on 2020-10-03 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywebsite', '0015_auto_20201001_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
