# Generated by Django 3.1.1 on 2020-10-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0016_myblog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='likes',
        ),
    ]
